### ISSUE TITLE
NPE when creating Rule details if Base- or Matching- Entity is empty

### ISSUE THREAD

**Issue by IskandarovRost** [adhawan325/cuba-duplicate-tools-addon#2]
1) Open Duplicate Detection Rules browser
2) Create a new Rule, do not save it.
3) Not selecting Base Entity or Matching Entity, create a new Rule detail 

AR: NPE
![image](https://user-images.githubusercontent.com/19840141/45157905-73a28480-b1f3-11e8-8d75-61a8da9d7b89.png)

**Comment by adhawan325** [comment]
@IskandarovRost  - fixed
