### ISSUE TITLE
Invalid VCS link on Bintray

### ISSUE THREAD

**Issue by jreznot** [adhawan325/cuba-duplicate-tools-addon#4]
There is incorrect link to VCS in Bintray info:
https://bintray.com/adhawan325/cuba-duplicate-tools-addon/nondta

![image](https://user-images.githubusercontent.com/1066152/45344195-1cfec700-b5b4-11e8-88ca-cbb2f385cae4.png)

**Comment by adhawan325** [comment]
@jreznot 

Hi Yuriy!

This is now fixed.  Thanks!
